title: "Bora Atakan"
author:
  name: Bora Atakan
  email: a.boraatakan@gmail.com

description: >
  Bora Atakan - Computer Science student at the University of Waterloo

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Uncomment if you want absolute URLs in SEO tags.
url: "https://anilboraatakan.github.io"
baseurl: ""

social:
  github: "https://github.com/AnilBoraAtakan"
  linkedin: "https://www.linkedin.com/in/anil-bora-atakan/"

exclude:
  - Gemfile
  - Gemfile.lock
  - makefile
  - README.md
  - .gitignore
