title: "Anil Bora Atakan Personal Website"
author:
  name: Anil Bora Atakan
  email: a.boraatakan@gmail.com

description: >
  Anil Bora Atakan - Personal Website

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md

minima: 
  skin: classic

  # baseurl: "/my-github-pages-site" # Replace with your repo name
  # url: "https://anilboraatakan.github.io"

  # markdown: kramdown

  social_links:
    - { platform: github, user_url: "https://github.com/AnilBoraAtakan" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/anıl-bora-atakan-6039a5247/" }

exclude:
  - Gemfile
  - Gemfile.lock
  - makefile
  - README.md
  - .gitignore